{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-exporter.secretName" . }}
  labels:
    {{- include "cloudflare-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cloudflare.existingSecret.apiTokenKey }}: {{ required "secret.apiToken is required when secret.create=true" .Values.secret.apiToken | quote }}
  {{ .Values.cloudflare.existingSecret.zoneTagsKey }}: {{ required "secret.zoneTags is required when secret.create=true" .Values.secret.zoneTags | quote }}
{{- end }}
